import {catalog,lexicalQuestion,passageQuestion,initializeStudy,recordStudyAnswer,dayKey} from './study.mjs?v=20260921-unified-v1';
import {setupStudyUI,explanation} from './study-ui.mjs?v=20260921-unified-v1';
import {blankState,normalizeState,maxLevel,activePool,masteredCount,buildQuestion,recordAnswer,rollBillReward,addReward,nextCorrectStreak} from './core.mjs?v=20260921-unified-v1';
import {initializeStorage,login,register,currentLocalUser,loadState,saveState,logout} from './storage.mjs';
import {buildPhraseQuestion} from './phrases.mjs?v=20260921-review';

const $=id=>document.getElementById(id),reliableZh=value=>value&&!/待人工|待確認/.test(value);
const libraries={},content={};
const mindmapIds=['05',...Array.from({length:63},(_,i)=>String(i+7).padStart(2,'0')),...Array.from({length:30},(_,i)=>String(i+71))];
let mindmaps=[],currentMindmap=null;
let state=blankState(),user=null,currentLibrary='basic',currentContent='basicReading',learnIndex=0,currentQuestion=null,storageMode='local',correctStreak=0,rewardTimer=null,phraseQuizType=null,detailItem=null;

async function json(path){const response=await fetch(path);if(!response.ok)throw new Error(`無法載入 ${path}`);return response.json();}
async function loadLibraries(){const [basic,advanced,phrases,basicReading,articles,cloze,readingTest,reviewedMindmaps]=await Promise.all([json('./data/basic.json'),json('./data/advanced.json'),json('./data/phrases.json?v=20260921-docx'),json('./data/basic-readings.json?v=20260921-unified-v1'),json('./data/advanced-articles.json?v=20260921-unified-v1'),json('./data/cloze-sets.json?v=20260921-unified-v1'),json('./data/reading-tests.json?v=20260921-unified-v1'),json('./data/mindmaps.json?v=20260921-unified-v1')]);Object.assign(libraries,{basic,advanced,phrases});content.mindmaps=reviewedMindmaps;content.phraseUnits=await json('./data/phrase-units.json?v=20260921-docx');Object.assign(content,{basicReading,articles,cloze,readingTest});const reviewed=new Map(reviewedMindmaps.map(item=>[item.id,item]));mindmaps=mindmapIds.map(id=>reviewed.get(id)||{id,title:`主題 ${Number(id)}`,image:`思維導圖/${id}.jpg`,status:'pending',words:[],questions:[]});}
function speak(text){if(!('speechSynthesis'in window))return alert('此瀏覽器不支援語音播放');speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='en-US';utterance.rate=.86;speechSynthesis.speak(utterance);}
function showScreen(name){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===name));window.scrollTo({top:0,behavior:'smooth'});if(name==='home'||name==='foundation-home')renderSummaries();if(name==='library')renderLibrary();if(name==='phrases')renderPhrases();if(name==='content-list')renderContentList();if(name==='content-detail')renderContentDetail();if(name==='mindmaps')renderMindmapGallery();if(name==='mindmap-detail')renderMindmapDetail();}
function label(key){return key==='basic'?'基礎 1200 單字':'進階 7200 單字';}
function librarySummary(key){const s=state.libraries[key],words=libraries[key]||[];return `Lv.${s.level}・已作答 ${s.answers} 題・熟練 ${masteredCount(words,s)} 字`;}
function renderWallet(){$('wallet-total').textContent=state.wallet.total;$('wallet-ones').textContent=state.wallet.ones;$('wallet-tens').textContent=state.wallet.tens;$('wallet-hundreds').textContent=state.wallet.hundreds;$('wallet-modal-total').textContent=state.wallet.total;}
function renderSummaries(){renderWallet();const daily=state.study?.daily;$('daily-home-status').textContent=daily?.day===dayKey()?`今天已完成 ${Object.keys(daily.answers).length}/${daily.questions.length} 題`:'每日 8 題，可中途續答';$('basic-summary').textContent=`1200 單字 ${libraries.basic?.length||0} 筆・閱讀 ${content.basicReading?.length||0} 篇`;$('advanced-summary').textContent=`單字 ${libraries.advanced?.length||0} 筆・片語 ${libraries.phrases?.length||0} 筆`;$('foundation-word-summary').textContent=librarySummary('basic');$('basic-reading-summary').textContent=`目前 ${content.basicReading?.length||0} 篇示範教材`;$('mindmap-summary').textContent=`共 ${mindmaps.length} 篇・已讀 ${state.mindMaps.read.length} 篇・已完成劍橋校對 ${mindmaps.filter(x=>x.status!=='pending').length} 篇`;}

function toggleMindmapList(key,id){const values=state.mindMaps[key],index=values.indexOf(id);index>=0?values.splice(index,1):values.push(id);state.updatedAt=Date.now();save();}
function openMindmap(id){currentMindmap=mindmaps.find(x=>x.id===id);if(!currentMindmap)return;if(!state.mindMaps.read.includes(id))state.mindMaps.read.push(id);save();showScreen('mindmap-detail');}
function renderMindmapGallery(){const query=$('mindmap-search').value.trim().toLowerCase(),favoritesOnly=$('mindmap-favorites-only').checked;const filtered=mindmaps.filter(item=>(!favoritesOnly||state.mindMaps.favorites.includes(item.id))&&(!query||`${item.id} ${item.title} ${(item.words||[]).map(x=>x.word).join(' ')}`.toLowerCase().includes(query)));$('mindmap-progress').textContent=`已讀 ${state.mindMaps.read.length} / ${mindmaps.length}`;$('mindmap-grid').innerHTML='';for(const item of filtered){const card=document.createElement('article');card.className='mindmap-card';const read=state.mindMaps.read.includes(item.id),favorite=state.mindMaps.favorites.includes(item.id);card.innerHTML=`<button class="mindmap-cover" aria-label="開啟${item.title}"><img src="${item.image}" alt="${item.title}" loading="lazy"></button><div><small>第 ${Number(item.id)} 篇 ${read?'・已讀':''}</small><h2>${item.title}</h2><span class="review-badge ${item.status}">${item.status==='reviewed'?'劍橋已校對':item.status==='needsReview'?'部分待人工確認':'待劍橋校對'}</span><button class="favorite-mini ghost" aria-label="${favorite?'取消收藏':'加入收藏'}">${favorite?'★':'☆'}</button></div>`;card.querySelector('.mindmap-cover').onclick=()=>openMindmap(item.id);card.querySelector('.favorite-mini').onclick=()=>{toggleMindmapList('favorites',item.id);renderMindmapGallery();};$('mindmap-grid').appendChild(card);}if(!filtered.length)$('mindmap-grid').innerHTML='<p class="panel empty-result">找不到符合條件的主題。</p>';}
function renderMindmapDetail(){const item=currentMindmap;if(!item)return showScreen('mindmaps');const index=mindmaps.indexOf(item),favorite=state.mindMaps.favorites.includes(item.id);$('mindmap-meta').textContent=`VISUAL TOPIC ${Number(item.id)}・${index+1} / ${mindmaps.length}`;$('mindmap-title').textContent=item.title;$('mindmap-image').src=item.image;$('mindmap-image').alt=`${item.title}思維導圖`;$('mindmap-favorite').textContent=favorite?'★ 已收藏':'☆ 收藏';$('mindmap-favorite').onclick=()=>{toggleMindmapList('favorites',item.id);renderMindmapDetail();};$('mindmap-prev').disabled=index===0;$('mindmap-next').disabled=index===mindmaps.length-1;$('mindmap-prev').onclick=()=>openMindmap(mindmaps[index-1]?.id);$('mindmap-next').onclick=()=>openMindmap(mindmaps[index+1]?.id);const ready=item.status!=='pending';$('mindmap-status').innerHTML=ready?`<div class="review-note ${item.status}"><b>${item.status==='reviewed'?'劍橋繁中釋義已校對':'部分詞彙待人工確認'}</b><span>翻譯來源：${item.source||'Cambridge English–Traditional Chinese Dictionary'}。不採用圖片中的簡體翻譯。</span>${item.sourceUrl?`<a href="${item.sourceUrl}" target="_blank" rel="noopener">查看劍橋來源</a>`:''}</div>`:'<div class="review-note pending"><b>本篇正在進行劍橋繁中校對</b><span>目前可先閱讀及收藏原圖；在查核完成前不顯示原圖簡體翻譯，也不產生未驗證題目。</span></div>';$('mindmap-learning').classList.toggle('hidden',!ready);if(!ready)return;$('mindmap-words').innerHTML='';for(const word of item.words){const row=document.createElement('div');row.className=`mindmap-word ${word.needsReview?'needs-review':''}`;row.innerHTML=`<button class="speak-mini" aria-label="播放 ${word.word}">🔊</button><div><b>${word.word}</b><span>${word.meaning}</span>${word.review?`<small>${word.needsReview?'⚠ ':''}${word.review}</small>`:''}${word.sourceUrl?`<a href="${word.sourceUrl}" target="_blank" rel="noopener">Cambridge</a>`:''}</div>`;row.querySelector('button').onclick=()=>speak(word.word);$('mindmap-words').appendChild(row);}$('mindmap-article').innerHTML=`<h3>${item.article.title}</h3><p>${item.article.text}</p><details><summary>顯示繁體中文翻譯</summary><p>${item.article.translation}</p></details><button id="speak-mindmap-article" class="ghost">🔊 播放英文短文</button>`;$('speak-mindmap-article').onclick=()=>speak(item.article.text);renderMindmapQuiz(item);}
function renderMindmapQuiz(item){const box=$('mindmap-quiz');box.innerHTML='';item.questions.forEach((question,index)=>{const block=document.createElement('div');block.className='inline-question';block.innerHTML=`<p><b>${index+1}. ${question.prompt}</b></p>`;const choices=document.createElement('div');choices.className='inline-choices';const feedback=document.createElement('p');feedback.className='feedback';question.choices.forEach(value=>{const button=document.createElement('button');button.textContent=value;button.onclick=()=>{if(choices.dataset.answered)return;choices.dataset.answered='yes';const correct=value===question.answer;choices.querySelectorAll('button').forEach(x=>{x.disabled=true;if(x.textContent===question.answer)x.classList.add('correct');});if(!correct)button.classList.add('wrong');const snapshot=passageQuestion(item,question,'mindmaps',index);recordStudyAnswer(state,snapshot,String(question.choices.indexOf(value)));const reward=rewardCorrect('mindmaps',`${item.id}-${index}`,correct);feedback.textContent=correct?`答對了！獲得 $${reward.total}`:`答案是 ${question.answer}`;feedback.className=`feedback ${correct?'good':'bad'}`;explanation(feedback,snapshot,String(question.choices.indexOf(value)));};choices.appendChild(button);});block.append(choices,feedback);box.appendChild(block);});}
function renderPhrases(){const s=state.libraries.phrases,p=libraries.phrases||[],reliable=p.filter(x=>reliableZh(x.meaningZh)).length;$('phrases-progress-pill').textContent=`共 ${p.length} 則`;$('phrases-progress-detail').innerHTML=`Unit 1–30・中文片語 <b>${reliable}</b> 則<br>已作答 <b>${s.answers}</b> 題・熟練 <b>${p.filter(x=>(s.mastery[x.id]||0)>=3).length}</b> 則<br>最近作答：${s.recent.length?s.recent.map(x=>x?'✅':'❌').join(' '):'尚無紀錄'}`;}
function renderLibrary(){const words=libraries[currentLibrary],s=state.libraries[currentLibrary];$('library-label').textContent=currentLibrary==='basic'?'FOUNDATION':'ADVANCED';$('library-title').textContent=label(currentLibrary);$('level-pill').textContent=`Lv.${s.level} / ${maxLevel(words)}`;$('library-back').onclick=()=>showScreen(currentLibrary==='basic'?'foundation-home':'advanced-home');$('progress-detail').innerHTML=`字庫載入 <b>${words.length}</b> 筆<br>目前開放 <b>${activePool(words,s).length}</b> 筆・熟練 <b>${masteredCount(words,s)}</b> 筆<br>最近作答：${s.recent.length?s.recent.map(x=>x?'✅':'❌').join(' '):'尚無紀錄'}`;$('start-meaning-quiz').disabled=currentLibrary==='advanced';$('start-meaning-quiz').title=currentLibrary==='advanced'?'來源詞表尚無可靠中文翻譯':'';}
let saveQueue=Promise.resolve();
function save(){
  renderSummaries();const snapshot=JSON.parse(JSON.stringify(state)),owner=user;
  saveQueue=saveQueue.then(()=>saveState(owner,snapshot)).then(()=>{$('study-sync-status').textContent='';return true;}).catch(error=>{console.error(error);$('study-sync-status').textContent='學習紀錄同步失敗，請檢查網路後再試；暫時不要關閉頁面。';return false;});
  return saveQueue;
}
function openLibrary(key){currentLibrary=key;showScreen('library');}
function renderLearn(){const pool=activePool(libraries[currentLibrary],state.libraries[currentLibrary]),word=pool[learnIndex%pool.length];$('learn-position').textContent=`${label(currentLibrary)}・${learnIndex+1} / ${pool.length}`;$('learn-word').textContent=word.word;$('learn-meaning').textContent=word.meaningPending?'英文單字學習':word.meaning;$('speak-word').onclick=()=>speak(word.word);}
function startLearn(){learnIndex=0;$('learn-back').onclick=()=>showScreen('library');renderLearn();showScreen('learn');}
function renderPhraseLearn(){
  const item=libraries.phrases[learnIndex%libraries.phrases.length];
  $('learn-position').textContent=`Unit ${item.lesson}・${learnIndex+1} / ${libraries.phrases.length}`;
  $('learn-word').textContent=item.phrase;
  const box=$('learn-meaning');box.replaceChildren();
  const meaning=document.createElement('b');meaning.textContent=item.meaningZh;box.appendChild(meaning);
  if(item.examples.length){const example=document.createElement('p');example.textContent=item.examples[0];box.appendChild(example);}
  const unit=content.phraseUnits.find(x=>x.unit===item.lesson);
  if(unit){const details=document.createElement('details'),summary=document.createElement('summary'),passage=document.createElement('p');summary.textContent=`閱讀 Unit ${item.lesson} 完整課文`;passage.textContent=unit.passage;passage.style.whiteSpace='pre-line';details.append(summary,passage);box.appendChild(details);}
  $('speak-word').onclick=()=>speak(item.phrase);
}
function startPhraseLearn(){currentLibrary='phrases';learnIndex=0;$('learn-back').onclick=()=>showScreen('phrases');renderPhraseLearn();showScreen('learn');}
function startQuiz(type){try{currentQuestion=buildQuestion(libraries[currentLibrary],state.libraries[currentLibrary],type);renderQuestion();$('quiz-back').onclick=()=>showScreen('library');showScreen('quiz');if(type==='audio')setTimeout(()=>speak(currentQuestion.answer.word),250);}catch(error){alert(error.message==='EMPTY_LIBRARY'?'此題型目前沒有可用資料':'題目資料不足');}}
function resetQuiz(){ $('next-question').textContent='下一題'; $('feedback').textContent='';$('feedback').className='feedback';$('next-question').classList.add('hidden');$('choices').dataset.answered='no';$('choices').innerHTML='';}
function renderQuestion(){const audio=currentQuestion.type==='audio';$('quiz-kind').textContent=audio?'聽音選英文':'中文選英文';$('quiz-level').textContent=`Lv.${state.libraries[currentLibrary].level}`;$('quiz-prompt-label').textContent=audio?'請播放發音':'中文意思';$('quiz-prompt').textContent=audio?'聽完後選出正確單字':currentQuestion.answer.meaning;$('replay-audio').classList.toggle('hidden',!audio);$('replay-audio').onclick=()=>speak(currentQuestion.answer.word);resetQuiz();for(const choice of currentQuestion.choices){const button=document.createElement('button');button.className='choice';button.textContent=choice.word;button.onclick=()=>answerQuestion(button,choice);$('choices').appendChild(button);}}
function showReward(reward){clearTimeout(rewardTimer);const bills=[['ones','1.png','$1'],['tens','10.png','$10'],['hundreds','100.png','$100']].filter(([key])=>reward[key]),bonus=reward.tens||reward.hundreds;$('bonus-title').classList.toggle('hidden',!bonus);$('reward-bills').innerHTML=bills.map(([key,src,label])=>`<img class="reward-${key}" src="${src}" alt="${label} 鈔票">`).join('');$('reward-total').textContent=`獲得 $${reward.total}`;$('reward-pop').className=`reward-pop ${reward.hundreds?'mega':bonus?'bonus':''}`;$('reward-pop').classList.remove('hidden');rewardTimer=setTimeout(()=>$('reward-pop').classList.add('hidden'),bonus?1900:1100);}
function rewardCorrect(moduleKey,itemId,correct){recordAnswer(state,moduleKey,itemId,correct,moduleKey==='basic'||moduleKey==='advanced'?maxLevel(libraries[moduleKey]):1);correctStreak=nextCorrectStreak(correctStreak,correct);if(!correct){save();return null;}const reward=rollBillReward(correctStreak);addReward(state,reward);showReward(reward);save();return reward;}
function answerQuestion(button,choice){if($('choices').dataset.answered==='yes')return;$('choices').dataset.answered='yes';const correct=choice.id===currentQuestion.answer.id;document.querySelectorAll('.choice').forEach(x=>{x.disabled=true;if(x.textContent===currentQuestion.answer.word)x.classList.add('correct');});if(!correct)button.classList.add('wrong');const snapshot=lexicalQuestion(currentQuestion,currentLibrary);recordStudyAnswer(state,snapshot,choice.id);const reward=rewardCorrect(currentLibrary,currentQuestion.answer.id,correct);$('feedback').textContent=correct?`答對了！獲得 $${reward.total}`:`答錯了，答案是 ${currentQuestion.answer.word}`;explanation($('feedback'),snapshot,choice.id);$('feedback').classList.add(correct?'good':'bad');$('next-question').classList.remove('hidden');}
function startPhraseQuiz(type){try{currentLibrary='phrases';phraseQuizType=type;currentQuestion=buildPhraseQuestion(libraries.phrases,state.libraries.phrases,type);$('quiz-back').onclick=()=>showScreen('phrases');renderPhraseQuestion();showScreen('quiz');}catch(error){alert('此題型目前可用資料不足');}}
function renderPhraseQuestion(){const q=currentQuestion,phraseChoice=q.type!=='phraseToZh';$('quiz-kind').textContent=q.type==='zhToPhrase'?'中文選片語':q.type==='phraseToZh'?'片語選中文':'例句克漏字';$('quiz-level').textContent=`Unit ${q.answer.lesson}`;$('quiz-prompt-label').textContent=q.type==='zhToPhrase'?'中文意思':q.type==='phraseToZh'?'英文片語':'請選出空格中的片語';$('quiz-prompt').textContent=q.type==='zhToPhrase'?q.answer.meaningZh:q.type==='phraseToZh'?q.answer.phrase:q.cloze;$('replay-audio').classList.remove('hidden');$('replay-audio').onclick=()=>speak(q.answer.phrase);resetQuiz();for(const choice of q.choices){const button=document.createElement('button');button.className='choice';button.textContent=phraseChoice?choice.phrase:choice.meaningZh;button.onclick=()=>answerPhraseQuestion(button,choice);$('choices').appendChild(button);}}
function answerPhraseQuestion(button,choice){if($('choices').dataset.answered==='yes')return;$('choices').dataset.answered='yes';const correct=choice.id===currentQuestion.answer.id,answerText=currentQuestion.type==='phraseToZh'?currentQuestion.answer.meaningZh:currentQuestion.answer.phrase;document.querySelectorAll('.choice').forEach(x=>{x.disabled=true;if(x.textContent===answerText)x.classList.add('correct');});if(!correct)button.classList.add('wrong');recordStudyAnswer(state,lexicalQuestion(currentQuestion,'phrases'),choice.id);const reward=rewardCorrect('phrases',currentQuestion.answer.id,correct);$('feedback').textContent=correct?`答對了！獲得 $${reward.total}`:`答錯了，答案是 ${answerText}`;{for(const [index,item] of currentQuestion.choices.entries()){const row=document.createElement('span');row.style.display='block';row.style.textAlign='left';row.style.marginTop='10px';row.style.lineHeight='1.6';const marker=item.id===currentQuestion.answer.id?' ✓ 正確答案':item.id===choice.id?'（你的選擇）':'';row.textContent=`${index+1}. ${item.phrase}：${item.meaningZh}${marker}`;$('feedback').appendChild(row);}}$('feedback').classList.add(correct?'good':'bad');$('next-question').classList.remove('hidden');}

const contentMeta={basicReading:{label:'FOUNDATION READING',title:'基礎閱讀',intro:'以基礎 1200 單字為主要詞彙來源，先閱讀與記憶，不強制大量作答。',back:'foundation-home'},articles:{label:'TOPIC ARTICLES',title:'主題文章',intro:'透過完整語境理解進階單字與片語；點擊重點詞可查看意思並播放發音。',back:'advanced-home'},cloze:{label:'CONTEXT CLOZE',title:'克漏字',intro:'每篇文章延伸多題，讓剛學過的單字與片語在語境中再次出現。',back:'advanced-home'},readingTest:{label:'READING TEST',title:'閱讀測驗',intro:'原創多益風格文章與理解題，和非考試型的主題文章分開。',back:'advanced-home'}};
function openContent(key){currentContent=key;showScreen('content-list');}
function renderContentList(){const meta=contentMeta[currentContent],items=content[currentContent]||[];$('content-label').textContent=meta.label;$('content-title').textContent=meta.title;$('content-intro').textContent=meta.intro;$('content-count').textContent=`${items.length} 筆示範`;$('content-back').onclick=()=>showScreen(meta.back);$('content-items').innerHTML='';for(const item of items){const button=document.createElement('button');button.className='content-card';button.innerHTML=`<span>Lv.${item.level}・${item.topic}</span><b>${item.title}</b><small>${item.questions?`${item.questions.length} 題`:`重點詞 ${item.targetWords.length} 個`}</small>`;button.onclick=()=>{detailItem=item;showScreen('content-detail');};$('content-items').appendChild(button);}const coverage=$('coverage-panel');coverage.classList.toggle('hidden',currentContent!=='basicReading');if(currentContent==='basicReading'){const known=new Set(libraries.basic.map(x=>x.word.toLowerCase())),covered=new Set(items.flatMap(x=>x.coveredWords.map(w=>w.toLowerCase())).filter(w=>known.has(w)));coverage.innerHTML=`1200 單字閱讀覆蓋率：<b>${covered.size} / ${known.size}</b>（${(covered.size/known.size*100).toFixed(1)}%）<br><small>此數字會隨後續核准的教材批次增加。</small>`;}}
function wordLookup(word){const normalized=word.toLowerCase(),basic=libraries.basic.find(x=>x.word.toLowerCase()===normalized),advanced=libraries.advanced.find(x=>x.word.toLowerCase()===normalized),phrase=libraries.phrases.find(x=>x.phrase.toLowerCase()===normalized);return basic||advanced||phrase;}
function renderContentDetail(){$('detail-meta').textContent=`Lv.${detailItem.level}・${detailItem.topic}`;$('detail-title').textContent=detailItem.title;$('detail-passage').textContent=detailItem.passage;$('detail-words').innerHTML='';for(const word of [...(detailItem.targetWords||[]),...(detailItem.targetPhrases||[])]){const button=document.createElement('button');button.className='word-chip';button.textContent=word;button.onclick=()=>{const found=wordLookup(word),meaning=found?.meaningPending?'':(found?.meaning||found?.meaningZh||found?.meaningEn||'');alert(meaning?`${word}\n${meaning}`:word);speak(word);};$('detail-words').appendChild(button);}renderActivity();}
function renderActivity(){const box=$('detail-activity');box.innerHTML='';if(!detailItem.questions?.length)return;const heading=document.createElement('h2');heading.textContent=currentContent==='cloze'?'文章延伸題':'閱讀理解題';box.appendChild(heading);detailItem.questions.forEach((question,index)=>{const block=document.createElement('div');block.className='inline-question';block.innerHTML=`<p><b>${index+1}. ${question.prompt}</b></p>`;const choices=document.createElement('div');choices.className='inline-choices';question.choices.forEach(value=>{const button=document.createElement('button');button.textContent=value;button.onclick=()=>{if(choices.dataset.answered)return;choices.dataset.answered='yes';const correct=value===question.answer;choices.querySelectorAll('button').forEach(x=>{x.disabled=true;if(x.textContent===question.answer)x.classList.add('correct');});if(!correct)button.classList.add('wrong');const snapshot=passageQuestion(detailItem,question,currentContent,index);recordStudyAnswer(state,snapshot,String(question.choices.indexOf(value)));const reward=rewardCorrect(currentContent,question.id,correct);feedback.textContent=correct?`答對了！獲得 $${reward.total}`:`答案是 ${question.answer}`;feedback.className=`feedback ${correct?'good':'bad'}`;explanation(feedback,snapshot,String(question.choices.indexOf(value)));};choices.appendChild(button);});const feedback=document.createElement('p');feedback.className='feedback';block.append(choices,feedback);box.appendChild(block);});}

document.querySelectorAll('[data-screen]').forEach(button=>button.addEventListener('click',()=>showScreen(button.dataset.screen)));document.querySelectorAll('[data-library]').forEach(button=>button.addEventListener('click',()=>openLibrary(button.dataset.library)));document.querySelectorAll('[data-content]').forEach(button=>button.addEventListener('click',()=>openContent(button.dataset.content)));
$('mindmap-search').oninput=renderMindmapGallery;$('mindmap-favorites-only').onchange=renderMindmapGallery;$('mindmap-image-button').onclick=()=>{$('mindmap-lightbox-image').src=currentMindmap.image;$('mindmap-lightbox').classList.remove('hidden');};function closeMindmapLightbox(){$('mindmap-lightbox').classList.add('hidden');}$('mindmap-lightbox-close').onclick=closeMindmapLightbox;$('mindmap-lightbox').onclick=event=>{if(event.target===$('mindmap-lightbox')||event.target===$('mindmap-lightbox-image'))closeMindmapLightbox();};document.addEventListener('keydown',event=>{if(event.key==='Escape')closeMindmapLightbox();});
$('start-learn').onclick=()=>{phraseQuizType=null;startLearn();};$('start-meaning-quiz').onclick=()=>{phraseQuizType=null;startQuiz('meaning');};$('start-audio-quiz').onclick=()=>{phraseQuizType=null;startQuiz('audio');};$('next-question').onclick=()=>phraseQuizType?startPhraseQuiz(phraseQuizType):startQuiz(currentQuestion.type);$('prev-word').onclick=()=>{learnIndex=Math.max(0,learnIndex-1);currentLibrary==='phrases'?renderPhraseLearn():renderLearn();};$('next-word').onclick=()=>{learnIndex++;currentLibrary==='phrases'?renderPhraseLearn():renderLearn();};$('open-phrases').onclick=()=>showScreen('phrases');$('start-phrase-learn').onclick=startPhraseLearn;$('start-phrase-zh').onclick=()=>startPhraseQuiz('zhToPhrase');$('start-phrase-en').onclick=()=>startPhraseQuiz('phraseToZh');$('start-phrase-cloze').onclick=()=>startPhraseQuiz('cloze');
$('logout').onclick=async()=>{await logout();location.reload();};$('wallet-button').onclick=()=>{$('wallet-modal').classList.remove('hidden');renderWallet();};$('wallet-close').onclick=()=>$('wallet-modal').classList.add('hidden');$('wallet-modal').onclick=event=>{if(event.target===$('wallet-modal'))$('wallet-modal').classList.add('hidden');};
async function submitAuth(mode){$('auth-error').textContent='';const username=$('username').value.trim(),password=$('password').value;if(!username||!password){$('auth-error').textContent='請輸入帳號和密碼';return;}if(mode==='register'&&!/^[A-Za-z0-9._-]{3,30}$/.test(username)){$('auth-error').textContent='帳號須為 3～30 個英文字母、數字、點、底線或連字號';return;}if(mode==='register'&&password.length<6){$('auth-error').textContent='密碼至少需要 6 個字元';return;}const button=mode==='register'?$('register-button'):$('login-button'),originalText=button.textContent;button.disabled=true;button.textContent=mode==='register'?'建立中…':'登入中…';try{user=mode==='register'?await register(username,password):await login(username,password);state=normalizeState(await loadState(user)||blankState());initializeStudy(state);$('current-user').textContent=user.username;$('auth-gate').classList.add('hidden');showScreen('home');await save();}catch(error){console.error(`Firebase ${mode} failed`,error);const messages={'auth/invalid-credential':'帳號或密碼錯誤','auth/email-already-in-use':'這個帳號已存在','auth/weak-password':'密碼至少需要 6 個字元','auth/operation-not-allowed':'Firebase 尚未啟用「電子郵件／密碼」登入','auth/network-request-failed':'無法連線 Firebase，請檢查網路與 localhost 設定'};$('auth-error').textContent=messages[error.code]||`${mode==='register'?'建立帳號':'登入'}失敗：${error.code||error.message||'未知錯誤'}`;}finally{button.disabled=false;button.textContent=originalText;}}
setupStudyUI({getState:()=>state,getCatalog:()=>catalog(libraries,content),getLibraries:()=>libraries,save,reward:rewardCorrect,showScreen,speak});
$('login-form').onsubmit=event=>{event.preventDefault();submitAuth('login');};$('register-button').onclick=()=>submitAuth('register');
try{await loadLibraries();const result=await initializeStorage();storageMode=result.mode;$('auth-note').textContent=storageMode==='firebase'?'使用獨立英文版 Firebase 雲端同步。':'目前使用獨立本機資料；填入英文版 Firebase 設定後可啟用雲端。';user=currentLocalUser();if(user){state=normalizeState(await loadState(user)||blankState());initializeStudy(state);$('current-user').textContent=user.username;$('auth-gate').classList.add('hidden');}renderSummaries();}catch(error){console.error('Initialization failed',error);$('auth-error').textContent='啟動失敗：'+(error.code||error.message);}
