import assert from 'node:assert/strict';
import {blankState,normalizeState,maxLevel,buildQuestion,recordAnswer,rollBillReward,addReward,nextCorrectStreak} from '../js/core.mjs';
import fs from 'node:fs';

const basic=JSON.parse(fs.readFileSync(new URL('../data/basic.json',import.meta.url)));
const advanced=JSON.parse(fs.readFileSync(new URL('../data/advanced.json',import.meta.url)));
assert.equal(basic.length,1200);
assert.ok(advanced.length>6000);
assert.ok(basic.every(x=>x.word&&x.meaning));
assert.ok(advanced.every(x=>x.word));
const state=blankState();
const meaningQuestion=buildQuestion(basic,state.libraries.basic,'meaning',()=>0.1);
const audioQuestion=buildQuestion(basic,state.libraries.basic,'audio',()=>0.2);
assert.equal(meaningQuestion.choices.length,4);
assert.equal(audioQuestion.choices.length,4);
assert.ok(meaningQuestion.choices.some(x=>x.id===meaningQuestion.answer.id));
recordAnswer(state,'basic',meaningQuestion.answer.id,true,maxLevel(basic));
assert.equal(state.libraries.basic.mastery[meaningQuestion.answer.id],1);
assert.equal(state.libraries.advanced.answers,0);
for(let i=0;i<5;i++)recordAnswer(state,'basic',basic[i].id,true,maxLevel(basic));
assert.equal(state.libraries.basic.level,2);
const restored=normalizeState(JSON.parse(JSON.stringify(state)));
assert.equal(restored.libraries.basic.level,2);
const legacy=normalizeState({coins:37,libraries:{}});
assert.deepEqual(legacy.wallet,{ones:37,tens:0,hundreds:0,total:37});
assert.deepEqual(legacy.mindMaps,{read:[],favorites:[]});
assert.ok(legacy.libraries.mindmaps);
const mindmapState=normalizeState({mindMaps:{read:['05','05',50],favorites:['100']}});
assert.deepEqual(mindmapState.mindMaps,{read:['05','50'],favorites:['100']});
const noBonus=rollBillReward(2,()=>0);
assert.deepEqual(noBonus,{ones:1,tens:0,hundreds:0,total:1});
const tenBonus=rollBillReward(3,()=>0);
assert.deepEqual(tenBonus,{ones:1,tens:1,hundreds:0,total:11});
const bothBonus=rollBillReward(10,()=>0);
assert.deepEqual(bothBonus,{ones:1,tens:1,hundreds:1,total:111});
const noHighBonus=rollBillReward(10,()=>.99);
assert.deepEqual(noHighBonus,{ones:1,tens:0,hundreds:0,total:1});
assert.equal(rollBillReward(3,()=>.10).tens,0);
assert.equal(rollBillReward(5,()=>.19).tens,1);
assert.equal(rollBillReward(10,()=>.29).tens,1);
assert.equal(nextCorrectStreak(0,true),1);
assert.equal(nextCorrectStreak(8,true),9);
assert.equal(nextCorrectStreak(9,false),0);
addReward(state,bothBonus);
assert.deepEqual(state.wallet,{ones:1,tens:1,hundreds:1,total:111});
assert.equal(state.coins,111);
console.log(`PASS basic=${basic.length} advanced=${advanced.length} wallet=${state.wallet.total} level=${restored.libraries.basic.level}`);
