import assert from 'node:assert/strict';
import fs from 'node:fs';
import {blankState,normalizeState} from '../js/core.mjs';
import {buildPhraseQuestion} from '../js/phrases.mjs';
import {recordPhraseReview,reviewCards,buildReviewQuestion} from '../js/phrase-review.mjs';
const phrases=JSON.parse(fs.readFileSync(new URL('../data/phrases.json',import.meta.url)));
const state=blankState(),answer=phrases[0];
const question=type=>buildPhraseQuestion(phrases,{mastery:{}},type,()=>.2,answer.id);
const q=question('zhToPhrase'),wrong=q.choices.find(x=>x.id!==answer.id);
recordPhraseReview(state,q,answer);
assert.equal(Object.keys(state.phraseMistakes).length,0);
recordPhraseReview(state,q,wrong,{now:10});
const q2=question('phraseToZh');
recordPhraseReview(state,q2,q2.choices.find(x=>x.id!==answer.id),{now:20});
assert.equal(Object.keys(state.phraseMistakes).length,1);
let card=state.phraseMistakes[answer.id];
assert.equal(card.wrongCount,2);assert.equal(Object.keys(card.errors).length,2);
assert.equal(card.errors.zhToPhrase.selectedId,wrong.id);
assert.equal(reviewCards(state.phraseMistakes,phrases,{unit:'2'}).length,0);
assert.equal(reviewCards(state.phraseMistakes,phrases,{type:'cloze'}).length,0);
const retry=buildReviewQuestion(card,phrases,'zhToPhrase',()=>0);
assert.deepEqual(new Set(retry.choices.map(x=>x.id)),new Set(q.choices.map(x=>x.id)));
assert.notDeepEqual(retry.choices,q.choices);
recordPhraseReview(state,retry,answer,{sessionId:'one'});
recordPhraseReview(state,retry,answer,{sessionId:'one'});
assert.equal(card.streak,1);
assert.equal(buildReviewQuestion(card,phrases).answer.id,answer.id);
recordPhraseReview(state,q,answer,{sessionId:'two'});
recordPhraseReview(state,q,answer,{sessionId:'three'});
assert.equal(card.streak,3);
assert.equal(reviewCards(state.phraseMistakes,phrases).length,0);
assert.equal(reviewCards(state.phraseMistakes,phrases,{status:'mastered'}).length,1);
recordPhraseReview(state,q,wrong,{now:30});
assert.equal(card.streak,0);assert.equal(card.wrongCount,3);
assert.equal(reviewCards(state.phraseMistakes,phrases).length,1);
assert.deepEqual(normalizeState(JSON.parse(JSON.stringify(state))).phraseMistakes,state.phraseMistakes);
assert.deepEqual(normalizeState({coins:9}).phraseMistakes,{});
assert.equal(normalizeState({coins:9}).wallet.total,9);
const duplicates=phrases.filter(p=>p.phrase==='to make out');
const duplicateState=blankState();
for(const item of duplicates){
  const dup=buildPhraseQuestion(phrases,{mastery:{}},'phraseToZh',()=>.2,item.id);
  recordPhraseReview(duplicateState,dup,dup.choices.find(x=>x.id!==item.id));
}
assert.equal(Object.keys(duplicateState.phraseMistakes).length,1);
assert.equal(Object.values(duplicateState.phraseMistakes)[0].wrongCount,duplicates.length);
for(const item of duplicates)assert.equal(reviewCards(duplicateState.phraseMistakes,phrases,{unit:String(item.lesson)}).length,1);
console.log('PASS merged errors, original retry, filters, three sessions, reopening, persistence');
