import assert from 'node:assert/strict';
import fs from 'node:fs';
import {blankState,normalizeState} from '../js/core.mjs';
import {catalog,materialize,recordStudyAnswer,initializeStudy,listCards,pendingItems,getDaily,answerDaily,ability,reviewQueue,dayKey} from '../js/study.mjs';
const read=name=>JSON.parse(fs.readFileSync(new URL(`../data/${name}.json`,import.meta.url)));
const libraries={basic:read('basic'),advanced:read('advanced'),phrases:read('phrases')};
const content={basicReading:read('basic-readings'),articles:read('advanced-articles'),readingTest:read('reading-tests'),cloze:read('cloze-sets'),mindmaps:read('mindmaps')};
const entries=catalog(libraries,content),state=blankState();
const date=n=>new Date(2026,8,n,12);
const wrong=q=>q.choices.find(c=>c.id!==q.answerId).id;
let seed=81;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);
const q=materialize(entries.find(e=>e.kind==='word'),libraries,{random});
recordStudyAnswer(state,q,q.answerId,{now:date(20)});
assert.equal(Object.keys(state.study.cards).length,0);
recordStudyAnswer(state,q,wrong(q),{now:date(20)});
const item=state.study.cards[q.cardKey].items.lexical;
recordStudyAnswer(state,q,q.answerId,{practice:true,now:date(20)});
assert.equal(item.dates.length,0,'same-day correction cannot count');
recordStudyAnswer(state,q,q.answerId,{practice:true,now:date(21)});
recordStudyAnswer(state,q,q.answerId,{practice:true,now:date(21)});
assert.equal(item.dates.length,1);
recordStudyAnswer(state,q,q.answerId,{now:date(22)});
assert.equal(item.dates.length,1,'ordinary correct answer is not a review');
recordStudyAnswer(state,q,q.answerId,{practice:true,now:date(22)});
recordStudyAnswer(state,q,q.answerId,{practice:true,now:date(23)});
assert.equal(listCards(state,{status:'mastered'}).length,1);
recordStudyAnswer(state,q,wrong(q),{now:date(23)});
assert.equal(item.dates.length,0);
assert.equal(listCards(state).length,1);
assert.equal(item.due,'2026-09-24');

const articleQuestions=entries.filter(e=>e.module==='readingTest'&&e.item.id==='rt001').map(e=>materialize(e,libraries));
for(const x of articleQuestions)recordStudyAnswer(state,x,wrong(x),{now:date(20)});
const article=state.study.cards[articleQuestions[0].cardKey];
assert.equal(Object.keys(article.items).length,2);
for(const d of [21,22,23])recordStudyAnswer(state,articleQuestions[0],articleQuestions[0].answerId,{practice:true,now:date(d)});
assert.equal(pendingItems(article).length,1,'mastery is per article question');
assert.equal(listCards(state,{kind:'reading'}).length,1);
const retry=reviewQueue(state,entries,libraries,{kind:'reading'},random);
assert.equal(retry.length,1);assert.ok(retry[0].passage);assert.ok(retry[0].evidence);

const first=blankState(),daily=getDaily(first,entries,libraries,{now:date(21),random});
assert.equal(daily.questions.length,8);
assert.deepEqual(Object.fromEntries(['word','phrase','reading','cloze'].map(k=>[k,daily.questions.filter(q=>q.kind===k).length])),{word:3,phrase:2,reading:1,cloze:2});
assert.equal(new Set(daily.questions.map(q=>`${q.cardKey}/${q.itemKey}`)).size,8);
assert.equal(new Set(daily.questions.filter(q=>q.kind==='cloze').map(q=>q.cardKey)).size,1);
assert.equal(getDaily(first,entries,libraries,{now:date(21),random}),daily);
assert.ok(answerDaily(first,0,daily.questions[0].answerId,{now:date(21)}).correct);
assert.equal(answerDaily(first,0,daily.questions[0].answerId,{now:date(21)}),null,'double submit is ignored');
assert.equal(answerDaily(first,1,daily.questions[1].answerId,{now:date(22)}),null,'yesterday session cannot submit today');
const restored=normalizeState(JSON.parse(JSON.stringify(first)));
assert.deepEqual(getDaily(restored,entries,libraries,{now:date(21)}),daily);
assert.ok(restored.study.daily.answers[0]);
assert.notEqual(getDaily(restored,entries,libraries,{now:date(22),random}).day,daily.day);
initializeStudy(first).performance.word=Array(10).fill(true);
first.study.performance.reading=Array(10).fill(false);
assert.equal(ability(first,'word'),3);assert.equal(ability(first,'reading'),1);
const next=getDaily(state,entries,libraries,{now:date(24),random});
assert.ok(next.questions.some(x=>x.cardKey===q.cardKey),'due wrong word is scheduled');

for(const entry of entries.filter(e=>e.q)){
 const question=materialize(entry,libraries);
 assert.ok(question.choices.every(c=>c.translation&&c.explanation));
 assert.ok(question.evidence&&question.passage.includes(question.evidence),`${question.itemKey} evidence belongs to passage`);
 assert.ok(question.choices.some(c=>c.id===question.answerId));
}
const old=blankState();old.phraseMistakes.x={wrongCount:2,lastWrongAt:123,errors:{zhToPhrase:{question:{type:'zhToPhrase',answer:libraries.phrases[0],choices:libraries.phrases.slice(0,4),cloze:''},selectedId:libraries.phrases[1].id,count:2,at:123}}};
initializeStudy(old);initializeStudy(old);
assert.equal(Object.values(old.study.cards)[0].wrongCount,2,'legacy migration is idempotent');
assert.equal(dayKey(new Date(2026,8,21,0,1)),'2026-09-21');
console.log('PASS unified mistakes, date mastery, article progress, daily quotas/resume/idempotency, adaptation, evidence, migration');
